### ISSUE TITLE
Option to disable line padding for intraline differences

### ISSUE THREAD

**Issue by evandrocoan** [DougTy/sublime-compare-side-by-side#11]
I want to not shift lines when there are just changes on it. Example, Currently is like this:
![image](https://cloud.githubusercontent.com/assets/5332158/18322208/dbb7b836-7507-11e6-8953-4ef2998184c6.png)

I want to be like this:
![image](https://cloud.githubusercontent.com/assets/5332158/18322263/4ab80146-7508-11e6-895b-a981b267f89b.png)

May be added a option to disable the Minimap automatically when on diff mode?

**Comment by DougTy** [comment]
I had experimented with this before, but ran into some issues. Definitely a good feature to have though. I'll take another crack at it as soon as I have the time. Thanks!

**Comment by DougTy** [comment]
Added in #23
