### ISSUE TITLE
Jump to next difference not working

### ISSUE THREAD

**Issue by aaaxx** [DougTy/sublime-compare-side-by-side#12]
According to https://github.com/DougTy/sublime-compare-side-by-side/issues/4 the shortcut is Alt+Shift+Down/Up, but it doesn't seem to work and I can't find the option for it in Key Bindings.

**Comment by DougTy** [comment]
Huh, looks like this broke with a Sublime update, it was definitely working before. :(

Should be fixed now. Thanks for the heads up.
