### ISSUE TITLE
letters missing in selection comparison view

### ISSUE THREAD

**Issue by whismerhill** [DougTy/sublime-compare-side-by-side#14]
one side is fine
the other side will show something like this : `		-- OPTION HERE : if disableunequip is true = do not switch back to previous item in hand and leave whatever we were working with in hand.

		if not disableunequip then

			print("switch to previous equipped item 3 ?")
			if playercontroller.autoequip_lastequipped then
				-- playercontroller.inst.components.locomotor:PushAction(BufferedAction(playercontroller.inst, nil, ACTIONS.EQUIP, playercontroller.autoequip_lastequipped), true)

				if type(layercontroller.autoequip_lastequipped) == "string" and not playercontroller.inst.components.inventory:IsFull() then

					playercontroller.inst.components.locomotor:PushAction(BufferedAction(playercontroller.inst, nil, ACTIONS.UNEQUIP, playercontroller.inst.components.inventory:GetEquippedItem(EQUIPSLOTS.HANDS)), true)

				elseif type(layercontroller.autoequip_lastequipped) == "table" then

					playercontroller.inst.components.locomotor:PushAction(BufferedAction(playercontroller.inst, nil, ACTIONS.EQUIP, playercontroller.autoequip_lastequipped), true)
				end
				playercontroller.autoequip_lastequipped = nil
			end
		end
`
I tripled verified and the original selected text is fine, in the code above there is "layercontroller" instead of "playercontroller" like it should.

**Comment by DougTy** [comment]
The plugin shouldn't be modifying any text like that. Can you provide two pieces of code that, when compared, will reproduce this issue? Is this on Sublime 2 or 3? How are you beginning the comparison (by selection, with active tab, right click > "compare with..."?)

**Comment by whismerhill** [comment]
here's the original code I had trouble with http://pastebin.com/XpsLbdvN
I didn't try much beside this to be honest, I used pastebin cause the code tag didn't work out like it should in my first post.
this is with sublime text 3
I use select the text,  rightclick - mark selection for comparison, for both
then right click again - compare selection
