### ISSUE TITLE
Option to ignore whitespace differences?

### ISSUE THREAD

**Issue by MMMcMahon** [DougTy/sublime-compare-side-by-side#16]
Please consider adding an option to ignore differences in whitespace.  
I have to compare files where one uses tabs and the other uses a combination of spaces and tabs  Doing the preliminary find-and-replace gets pretty tedious and I think incorporating such a change shouldn't be too hard... ?  

Thanks for the best comparison tool I've found!

**Comment by DougTy** [comment]
Good idea.

Looking into it, the diffing library that I'm using behind the scenes doesn't appear to support ignoring whitespace. I have however figured out a somewhat hacky workaround that seems to work alright, though it will need some testing before making it live.

If you're still interested and would like to try it out for yourself, you can download a zip of the experimental branch [here](https://github.com/DougTy/sublime-compare-side-by-side/archive/experimental.zip). Please let me know how this works for you, and if you happen to notice any unintentional side effects that I may have missed. Once we can be sure these changes are stable, I'll release the update.

Thanks! Glad you like the plugin.

**Comment by Razzeee** [comment]
@DougTy 
should it be enough to just throw it into the packages folder?
No new option for this added? (I would prefer that)

**Comment by ildarkhasanshin** [comment]
> No new option for this added?
option is available in the branch *experimental*

**Comment by DougTy** [comment]
@Razzeee Yes, you should be able to just stick it in your packages folder. If that doesn't work, try removing the package from package control first. A new `ignore_whitespace` option (defaults to false, so be sure to change that in your user settings) has been added in the experimental branch, [downloadable here](https://github.com/DougTy/sublime-compare-side-by-side/archive/experimental.zip).

**Comment by Razzeee** [comment]
Works as advertised thanks.

**Comment by DougTy** [comment]
Oops, forgot about this! As it seems to be working without issue, I've merged into master.

**Comment by am3000** [comment]
Just adding "ignore_whitespace":true to the user settings doesn´t seem to do the trick.
How exactly do I have to add it?
Using Sublime Text 3.
Thanks
