### ISSUE TITLE
compare with not working

### ISSUE THREAD

**Issue by gg4u** [DougTy/sublime-compare-side-by-side#17]
Hi, just installed the packacke.
I see compare with option on right-click menu, but does not trigger anything, nor compare with active tag.

What could be the issue? maybe a missing configuration?

**Comment by DougTy** [comment]
Try hitting Ctrl+~ to open the console, are there any errors there? Also, are you on Sublime Text 2 or 3?

**Comment by DougTy** [comment]
As you haven't responded in a while & I cannot reproduce any error, I'll assume you no longer need help and will close this issue. Please let me know if the problem persists and I'll reopen. Thanks.
