### ISSUE TITLE
Persistent Session Issues

### ISSUE THREAD

**Issue by Augustus061193** [DougTy/sublime-compare-side-by-side#2]
Close A Compare Window as the last Sublime Document and next time Sublime opens Compare Window pops up and couldn't open Normal Sublime Window. 

Suggestion: Revert the session to the last non Comparison window used.

**Comment by DougTy** [comment]
I've run into this a couple times myself as well, but unfortunately I don't think it can be easily solved.

Been doing some research, but I haven't been able to figure out an acceptable solution yet.

The best option right now I think is to just be sure to close comparison windows when you're done using them and before any other windows when exiting. It's easy to make mistakes though, so a more automated solution is definitely necessary.

I'll keep this issue open and update it once I've made some progress. Thanks!

**Comment by Augustus061193** [comment]
Currently there is a workaround to just delete <i>Session.sublime_session</i> file at

OS X: ~/Library/Application Support/Sublime Text 2
Windows: %APPDATA%\Sublime Text 2
Linux: ~/.config/sublime-text-2

**Comment by DougTy** [comment]
Apologies for the long wait, it was a struggle trying to find a clean solution to this problem.
I've addressed this in cfe4214. Package Control should update you when you next launch Sublime.

While it won't fix a user's session layout after it's been messed up, it will stop the user from closing their last normal (non-comparison) window before they close all comparison windows first. By ensuring that a normal window is closed last, it shouldn't get Sublime stuck in the double-column layout anymore.

Unfortunately, Sublime Text 2's `on_close` event doesn't seem to fire properly when a window is closed (only when a view is closed), so this solution will only work on Sublime Text 3.

**Comment by Augustus061193** [comment]
Awesome. :+1:
