### ISSUE TITLE
Make it default diff tool

### ISSUE THREAD

**Issue by apair** [DougTy/sublime-compare-side-by-side#21]
Is there any config that make `Compare Side by Side` default diff tool of ST3 ?

**Comment by DougTy** [comment]
As far as I know, there is no way to override or hide the built-in "Diff files" context menu action for project files. However, you should have the context menu actions [defined by this plugin](https://github.com/DougTy/sublime-compare-side-by-side/blob/master/Context.sublime-menu) in the same menu--do these not suffice/are they not showing up?

**Comment by DougTy** [comment]
As it's been a while with no response, I will be closing this issue. Please let me know if I have misunderstood & it should be reopened. Thanks.
