### ISSUE TITLE
Different color scheme

### ISSUE THREAD

**Issue by hadrielk** [DougTy/sublime-compare-side-by-side#27]
Hi,
what do you think about making the color scheme customizable? Not just the difference lines, but I mean the whole thing including background color - like the [BetterFindBuffer plugin](https://github.com/aziz/BetterFindBuffer). I could give it a try for the diff output and attach a screenshot, if you think it might be useful.

**Comment by DougTy** [comment]
This could go in [generate_colour_scheme](https://github.com/DougTy/sublime-compare-side-by-side/blob/master/sbs_compare.py#L76). Basically in there I'm getting the user's current theme XML, appending our custom colour strings to it, and saving it as a temporary new theme that the comparison window is set to. It should be possible to add an extra step to append a whole other `tmTheme` to that for overrides. My only issue with this is finding some sane defaults that will work well on both light and dark themes--perhaps disabled by default? I personally don't have a use case for this, but it should be doable.

**Comment by hadrielk** [comment]
Oh it would definitely only be an opt-in type thing, leaving the default behavior to what it is now.

**Comment by hadrielk** [comment]
So I've been playing with the idea and I see what you mean - given all the various color scheme people use for various file syntaxes, I'm not sure it's possible to pick sane background+foreground colors without having the user specify the details per syntax type... which would be nuts. So I'm canceling this idea. :)
