### ISSUE TITLE
Comparing option is grayedout since the new 1.17 update

### ISSUE THREAD

**Issue by Friss07** [DougTy/sublime-compare-side-by-side#34]
Hi and thanks for this great plugin, 
however, since the 1.17 update, the comparing option is grayed out, at least in my case.

![st2_c2c_bug](https://user-images.githubusercontent.com/12460721/33376227-2ecd059c-d50d-11e7-92b8-ddc4addcaace.png)

I use ST 2 (2.0.2 build 2221) on win 10 x64.

Maybe I am wrong somewhere but yet everything was working fine before this update.
Thanks in advance for checking this out.

My dirty solution is to backup the 1.17 sbs_compare.py and replace with the 1.16.2 one, sorry I am not familiar with python

**Comment by DougTy** [comment]
Oops, looks like I broke something for ST2 in that update. Sorry about that.
Patched, should be working now. Thanks for reporting this!
