### ISSUE TITLE
Comparing option is grayedout ST3

### ISSUE THREAD

**Issue by AlanSmithe** [DougTy/sublime-compare-side-by-side#35]
Hi,
I saw a closed issue with the grayedout option in ST2. I have the same problem with ST3. 
I just installed this plugin on my Osx ST3 build 3143 so I don't know if it ever worked on ST3 or if I made an mistake....

**Comment by DougTy** [comment]
Thanks for letting me know about this. The plugin should work on both ST2 and ST3.

Unfortunately, I can't reproduce this with ST3 3143 on Arch Linux. I believe it may be an OSX-specific bug of sorts, but I don't have an OSX machine myself to debug.

Would you kindly check the console `Ctrl + ~` and see if there's any errors in there related to the plugin? Thanks.

**Comment by AlanSmithe** [comment]
I'm very sorry to have bothered you. As soon that I saw that the console didn't have any output related to your plugin I moved the sublime-compare-side-by-side-master folder from the packages/User folder to the packages folder and now it works likes a charm.

**Comment by DougTy** [comment]
No bother! Glad you got it reaolved.
