### ISSUE TITLE
Intraline diff - unchanged text coloring

### ISSUE THREAD

**Issue by piotrgajow** [DougTy/sublime-compare-side-by-side#38]
It would be more readable if the unchanged text in the intraline diff would not be highlighted, or the colour would be different then regular removed/added colour. 

Currently, it is quite confusing when changed removed and added lines are next to each other.

**Comment by DougTy** [comment]
Apologies for late reply. This shouldn't be too hard to do, just adding two new colour settings and using them when the lines have a diff -- like how GitHub displays red and green still, but much lighter colours. I unfortunately don't have a great deal of time right now so I'm not sure when I'll be able to get to this, but if someone else would like to take this up, it should be relatively straight forward!

**Comment by piotrgajow** [comment]
I might try doing it myself, it could be good opportunity to learn some python :). I could not find a contribution guide, do you have any here?

**Comment by DougTy** [comment]
Unfortunately I don't have a contribution guide, but so long as the code works, has been tested not to break other functionality, and isn't doing anything too funky, I'm happy to accept the PR. There are no dependencies and there isn't any kind of building necessary, just fork on GitHub & clone into your Sublime's packages directory. Whenever you save the file, Sublime will automatically reload the plugin for you -- just be sure to unsubscribe from the current version of the plugin on Package Control if you've done that, or the menus may be duplicated. Please let me know if you have any questions.

**Comment by piotrgajow** [comment]
Ok, I have added pull request for this. Please take a look at it in some spare time, and let me know what you think about it.
