### ISSUE TITLE
Jumping to Line Changes

### ISSUE THREAD

**Issue by Mike8723** [DougTy/sublime-compare-side-by-side#4]
It would be nice to have the ability to jump to the lines that are different. Having an option to go to next and go to previous.

**Comment by DougTy** [comment]
Good idea, just added this! Sorry it took so long, been busy.
You should get the update next time you launch Sublime.

By default the hotkeys are Alt+Shift+Down for next, and Alt+Shift+Up for previous.

Thanks!
