### ISSUE TITLE
Better color schema

### ISSUE THREAD

**Issue by Daijobou** [DougTy/sublime-compare-side-by-side#43]
Hello, great package. I use pspad (freeware) that have this feature too in actual a little better way.

1. I not understand why left and right side have different colors, thats not more helpful as both have the same color and "green" is very bad visible in minimap.
2. pspad difference in 3 colors between lines that missing on left side, lines that missing on right side and lines that change partly.
3. The text in minimap is not useful at all, you should only show lines with differences, without text. So its much more better visible.

Thanks!

**Comment by DougTy** [comment]
Hi @Daijobou,

The default colours will mimic a standard diff in GitHub (and most code editors for that matter), but all colours can be customized in your settings if these defaults aren't to your liking. (`Preferences > Package Settings > Compare Side-by-Side`) There are separate colours for each side both for when a whole line is different, as well as highlights within a line for when just part of it is different, so 4 colours total. You can make the intraline colours the same if you just want 3 colours instead.

The minimap may be disabled with the `hide_minimap` setting if you don't find it useful or if it clashes with your chosen colour theme. I don't believe the Sublime API gives any control over what's displayed in the minimap, so it probably won't be possible to hide text or anything like that.

The idea of hiding unchanged lines has been thrown around before (as in issue #13) however this comes with a lot of issues as displayed line numbers in the diff would no longer correspond to actual line numbers in the files. That issue remain open in case anyone wants to have a try at it sometime.

I think I've covered everything, but please let me know if I've misunderstood.
Glad to hear you like the plugin.
