### ISSUE TITLE
Side-by-side window is not working properly

### ISSUE THREAD

**Issue by joaodiogo321** [DougTy/sublime-compare-side-by-side#44]
Hello!
When clicking "Compare with active tab" for example, the diff window is not showing any diff colours or even telling me what are the diffs between files. The initial line count popup does not appear as well. I have reinstalled the package and even sublime text but it still does not work.

It used to work in version 3126 but now I upgraded to 3176 and it just stopped. What should I do?

Thanks,
João

**Comment by DougTy** [comment]
The plugin is working for me on 3176 in Linux.

Can you please give me the following information to help better diagnose the issue:
1. Does the comparison window open (and just not display anything), or not at all?
2. What OS are you on?
3. Are there any errors in the Sublime console?
  (hit `Ctrl`+`~`, there may be different errors in the main window and the comparison window too.)

**Comment by joaodiogo321** [comment]
Hello Doug.

1.  The comparison window displays the text with the theme I chose for Sublime. However, it does not display the diff colours or any way to diff at all. It looks just like a regular divided window.
2.  My OS is Ubuntu 16.04.5 LTS
3.  is says:

> plugins loaded
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 283, in on_api_ready
>     m.plugin_loaded()
>   File "/home/joaobravo/.config/sublime-text-3/Installed Packages/Compare Side-By-Side.sublime-package/sbs_compare.py", line 20, in plugin_loaded
>     with open( os.path.join( folder, 'SBSCompareTheme.tmTheme' ), 'w', encoding='utf-8' ) as f:
> PermissionError: [Errno 13] Permission denied: '/home/joaobravo/.config/sublime-text-3/Packages/User/SBSCompareTheme.tmTheme'
> Package Control: Skipping automatic upgrade, last run at 2018-08-07 13:48:39, next run at 2018-08-07 14:48:39 or after

Maybe it is just a matter of setting permissions

**Comment by joaodiogo321** [comment]
Well... It was ahah thanks

**Comment by DougTy** [comment]
Glad to hear you've got it working.
Although I don't think having an unwriteable config folder is normal, I've added an error message when this happens so it can be caught and resolved easier if it comes up again for someone else. Thanks.
