### ISSUE TITLE
After package installation, tool is not available

### ISSUE THREAD

**Issue by link0127** [DougTy/sublime-compare-side-by-side#46]
Dear Team,

I cannot use this great tool after I installed the package through the sublime console. Package downloaded under the Installed package folder however after a sublime restart, no option appears if I'm right clicking to the tab(s).

Please help, what I'm doing wrong with the installation.

**Comment by DougTy** [comment]
1. Just to be clear, are you downloading through [Package Control](https://packagecontrol.io/) via Ctrl+Shift+P menu, or manually placing the folder under Installed Packages?
2. What OS & build of Sublime are you using?
3. Are there any errors in the Sublime console (Ctrl+~)

**Comment by link0127** [comment]
First of all thank you very much for the help.

1. First I tried to download through Package Control. After it's failed I tried using the "Manual" way.
2. I'm using Elementary OS & Sublime version 3.1.1, Build 3176
3. After pasting the code, there is no error appearing on the sublime console. A zip file downloaded to the "Installed Packages" folder and that's all. After that if I restart sublime I just cannot see the options.

Sorry I'm very new on the linux word (first OS that I'm using), maybe it's failing because of a basic mistake that I taking.

Thanks for your patience and support in advance.

**Comment by DougTy** [comment]
No worries, glad to help. Welcome to Linux! :)

It would be best to get the package installed through Package Control, as you'll receive automatic updates that way. Just in case you were using a different method, here's how I usually install packages:
1. Hit Ctrl+Shift+P to open up the command palette
2. Start typing "install" until you see the option "Package Control: Install Package", highlight it with the arrow keys, and hit enter
3. Start typing "Compare Side-By-Side", use arrow keys, and hit enter to select it
4. Restart Sublime & the package should be installed

If that doesn't work (are there any errors when attempting to install via Package Control?) then you can try installing manually, however installing packages directly to the Installed Packages folder requires a slightly different file format & putting a .zip in there won't work.

Instead, try extracting the zip file to the Packages folder. If one doesn't exist you can create it.
This is what mine looks like:
![image](https://user-images.githubusercontent.com/4277176/44077417-d9fb1f12-9f60-11e8-8642-13f13f464979.png)

Hope this helps.

**Comment by link0127** [comment]
Wonderful, the first step-by-step method you advised just worked like charm! :)

Now I'm able to use the tool. If I will notice anything else, I will let you know. It's great to be aware that this tool have an excellent support like you guys!

Thanks for your effort and thanks for the tool as well :)

**Comment by DougTy** [comment]
Glad you could get it sorted! Enjoy the plugin
