### ISSUE TITLE
Feature Request: Command to Select Added/Removed regions

### ISSUE THREAD

**Issue by hrobertson** [DougTy/sublime-compare-side-by-side#54]
Having compared two files, I want to select all parts that have been removed from one of the files.

I had a look at the source and tried `window.views()[1].get_regions('diff_intraline-A')` in the console but the result is empty.

**Comment by DougTy** [comment]
So sorry for the massive delay, I've been largely without a computer for a while and realize this is probably too late to be useful for you now. However, I've added a new command to do this, hopefully it may be useful in the future & to others.

Via the command pallete (`Ctrl+Shift+P`): `Select compared text...`  
You can select removed text (from the left view) or added text (from the right view)  
It's not terribly optimized (might be a bit slow for large files), and you need to click in the view you want to be copying from first, but it should work alright. Hopefully I'm not too late.

**Comment by hrobertson** [comment]
Thank you @DougTy ! I really appreciate it.

You're right that the specific case that prompted me to make this request has passed, but I'm sure it'll be very useful in the future.

There's certainly no need to apologise! This is FOSS that you created and maintain with no obligation to anyone.
If I was desperate for the functionality I could have spent the time to work out how to implement it and submitted a PR, but with zero experience working on ST plugins I decided to just extracted the differences manually.

So again, thanks for your work.
