### ISSUE TITLE
Cant install the plugin from the plugin manager

### ISSUE THREAD

**Issue by monti84** [DougTy/sublime-compare-side-by-side#57]
> Package Control: Error downloading package. HTTP error 500 downloading https://codeload.github.com/DougTy/sublime-compare-side-by-side/zip/v1.20.0.

**Comment by DougTy** [comment]
There was a major [Github outage](https://www.githubstatus.com/) earlier today that was likely causing this. Everything seems to be working now & I'm able to download the plugin from package control.
