### ISSUE TITLE
UnicodeEncodeError: 'charmap'

### ISSUE THREAD

**Issue by JohnBarry216** [DougTy/sublime-compare-side-by-side#6]
Hi,

I'm not sure if anyone else has experienced this, but a few weeks (maybe a month) ago Compare Side-by-Side just suddenly stopped working for me (tried on 2 separate windows 10 computers). When i run the compare, the two files come up in the new window like they are suppose to, but no highlighting was done. Below is an error i get in the sublime console.

Traceback (most recent call last):
  - File "C:\Development\Editors\Sublime Text 3\sublime_plugin.py", 
- line 574, in run_
    return self.run(edit)
  - File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\sublime-compare-side-by-side-master\sbs_compare.py", 
- line 495, in run
    on_click( 0 )
  - File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\sublime-compare-side-by-side-master\sbs_compare.py", 
- line 454, in on_click
    create_comparison( view1_contents, view2_contents, syntax, False, openTabs[index][0] )
  - File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\sublime-compare-side-by-side-master\sbs_compare.py", 
- line 424, in create_comparison
    self.colours = generate_colour_scheme( view1 )
  - File "C:\Users\John\AppData\Roaming\Sublime Text 3\Packages\sublime-compare-side-by-side-master\sbs_compare.py", 
- line 140, in generate_colour_scheme
    f.write( data )
  - File "./encodings/cp1252.py", 
- line 19, in encode UnicodeEncodeError: 'charmap' codec can't encode character '\u03c0' in position 267: character maps to <undefined>

I was able to fix this at least for my self, but since i'm not a python programmer what i did may have been incorrect if others try to implement it.

In the file 'sbs_compare.py', i changed **line 139** 
from:
`with open( theme_file( abs=True ), 'w' ) as f:`
to:
`with open( theme_file( abs=True ), 'w' , encoding='utf-8') as f:`

Again, this has fixed the issue for me but i figured i should mention something about it.

-John

**Comment by DougTy** [comment]
Hey John,

Oops, my mistake leaving that out. Thanks very much for looking into this! Much appreciated.
Your fix is entirely correct, and I've released a patch containing it.

Thanks again,
Doug
