### ISSUE TITLE
Tab Context Menu item "Compare with active tab" doesn't work properly when a window has multiple tab groups

### ISSUE THREAD

**Issue by ahuff44** [DougTy/sublime-compare-side-by-side#7]
Reproduction steps:
1. Open up a sublime windows and create multiple groups (e.g. through the menu item `View > Layout > Columns: 2`)
2. Right click on a tab and choose "Compare with active tab"
3. The diff window will correctly fetch the active tab, but instead of comparing it with the tab you right clicked on, it will compare it with the tab from the first group that has the same index as the tab you clicked on (i.e. if I clicked on tab 4 in group 2, the diff will show the contents of tab 4 from group 0)

There's also some strange behavior going on if you click on the active tab itself and try to "Compare with active tab"

---------------

By the way, I love the plugin! Best diff plugin I've found so far.

I ran into this bug while I was trying to set something up so that I could easily diff the two visible files within a window with two tab groups -- is there any easy way to do that? Ideally I'd like to set up a key combination to run this for me

**Comment by DougTy** [comment]
Hi Andrew,
Sorry for the delay.

Thanks for the detailed reproduction steps, it should be fixed now.

I've also added some quick functionality to compare the active views in two groups like you proposed.
Haven't tested it a whole lot, so let me know if it doesn't work quite right. It does it by checking if the group and index args are at their default of -1, so I'm hoping it doesn't have any funky side effects.

`{ "keys": ["alt+k"], "command": "sbs_compare", "args": { "with_active": true, "group": -1, "index": -1 } }`

Glad you like the plugin!
Doug
