### ISSUE TITLE
command key failed to work in Ubuntu

### ISSUE THREAD

**Issue by colordancer** [DougTy/sublime-compare-side-by-side#8]
I compared between two large C files, with over 150,000 lines. A lot of differences were found, though some were not precise. While I press Shift + Alt + Up/Down to navigate, the command key mostly didn't work well. Any idea?

**Comment by DougTy** [comment]
Hi colordancer,

Can you elaborate a bit please?
Are the keys not functioning at all, or is there some specific strange behaviour?
When you push them it should scroll to the previous/next difference and center it on the screen.
You said that some differences weren't precise, is intraline diffing not working for you?

Just checked, the Shift+Alt+Up/Down hotkeys are working for me in Arch. I don't use Ubuntu myself so I can't be sure, but [it seems that these key combinations may be used for something else by default.](http://askubuntu.com/questions/171489/how-to-unbind-shift-alt-up-shortkey-in-12-04)

You can try using different hotkeys for the comparison plugin by copying the contents of [`Default (Linux).sublime-keymap`](https://github.com/DougTy/sublime-compare-side-by-side/blob/master/Default%20(Linux).sublime-keymap) to your `Key Bindings - User` file for Sublime and changing the keys there.

Are you using Sublime Text 2 or 3?

**Comment by DougTy** [comment]
As you haven't responded in over two weeks and I cannot reproduce the issue, I'll assume that resolved it for you. Please let me know if the issue persists.
