### ISSUE TITLE
A way to prevent the modal summary popup?

### ISSUE THREAD

**Issue by petemounce** [DougTy/sublime-compare-side-by-side#9]
![modal-summary](https://cloud.githubusercontent.com/assets/69720/16946433/658ddc68-4da1-11e6-93f6-5336902bb79f.PNG) shows up when I do a `compare with...` and stops me from alt-tabbing (windows 10) over to the diff. 

Is there a way to turn that off? Or basically anything that makes it non-modal and/or part of the diff window (maybe a tab down the middle that's pre-selected so it can be scanned then closed via ctrl+w quickly?)?

I'm on a multi-monitor setup, and the diff + modal appeared on my default monitor instead of the same monitor that my sublime text was open on, too - that made me initially think it had hung sublime (since I couldn't see immediately that something had happened, and the modal stopped every input).

**Comment by DougTy** [comment]
Hi Peter,

You can turn the alert off by changing the `line_count_popup` option in the settings file.
To get to it: *Preferences -> Package Settings -> Compare Side-By-Side -> copy from Default to User*

Does this solve the issue for you?

**Comment by petemounce** [comment]
Hi Doug - I've created
```json
{
  "line_count_popup": false
}
```
within `C:\Users\<my user>\AppData\Roaming\Sublime Text 3\Packages\User\SBSCompare.sublime-settings`.

That removed the popup, but only *after* I restarted sublime.

Thanks!

**Comment by DougTy** [comment]
Glad to hear. Happy to help.
